### ISSUE TITLE
Corner Radius for Listbox

### ISSUE THREAD

**Issue by Touseefelahi** [Actipro/Avalonia-Controls#9]
Corner radius for list box doesn't show curve.

Sample image when corner radius is set to 5
![image](https://github.com/Actipro/Avalonia-Controls/assets/20659468/311d988e-8e95-42ae-b26f-6fe7081f3e24)

It feels like the ListBox, DataGrid, Calendar control corners are very sharp by default

**Comment by Touseefelahi** [comment]
My bad, I had to set Background color to transparent

**Comment by billhenn** [comment]
Hello,

Yes, list controls in our theme have square corners by default.  You can override the `ListCornerRadius` theme asset to alter that default if you wish.

Borders in Avalonia don't clip their contents by default so we have to add a workaround in templates for scenarios like that.  We have updated our templates for the list controls in the next maintenance release v23.1.3 so that rounded corners (when set) render better without a transparent background needing to be set.
